### ISSUE TITLE
Revert reason code doesn't work with a Parity node

### ISSUE THREAD

**Issue by liamaharon** [pertsev/web3_utilz#3]
the `web3.eth.call` call throws a generic `VM execution error` error when sent to a Parity node. instead, you need to call `trace_replayTransaction` with the transaction hash and ["trace"] as parameters (https://wiki.parity.io/JSONRPC-trace-module#trace_replaytransaction) then pull the `output` property off the response. 

will open a PR shortly

**Comment by liamaharon** [comment]
https://github.com/pertsev/web3_utilz/pull/4

**Comment by KentonPrescott** [comment]
Thank you @liamaharon ! This is much help
